name: Python Cluster Compare (pyCC)

on:
  push:
    branches:
      # - "*" # matches every branch that doesn't contain a '/'
      # - "*/*" # matches every branch containing a single '/'
      - "**" # matches every branch
      # - "!main" # excludes master
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
        shell: bash

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     # pip install .[dev]
      #     pip install poetry
      #     poetry install
      #   shell: bash

      # - name: Lint with ruff
      #   run: |
      #     poetry run ruff check .
      #   shell: bash

      #   # continue-on-error: true

      # - name: Lint with mypy
      #   run: |
      #     poetry run mypy .
      #   shell: bash

      #   # continue-on-error: true

      # - name: Build documentation
      #   run: |
      #     poetry run sphinx-build -b html docs/source docs/_build/html
      #   shell: bash

      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   if: github.ref == 'refs/heads/main'
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./docs/_build/html

      # - name: Test with pytest
      #   run: |
      #     python -m pip install pytest
      #     python -m pip install pytest-cov
      #     poetry run pytest -v -x
      #   shell: bash

      # - name: Test Coverage
      #   run: |
      #     python -m pip install coverage
      #     poetry run coverage report
      #     poetry run coverage html
      #   shell: bash